"""Build a single self-contained HTML documentation site from the markdown docs.

    python -m app.docsite        # writes docs/index.html

Converts README / PLAN / METRICS / DATA_DICTIONARY to one styled, offline HTML
page with a sidebar. Re-run after editing any doc (DATA_DICTIONARY is itself
generated by `python -m app.datadict`).
"""
from __future__ import annotations

import pathlib
import re

import markdown

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = [
    ("readme", "Overview", "README.md"),
    ("metrics", "Metrics", "METRICS.md"),
    ("data-dictionary", "Data Dictionary", "DATA_DICTIONARY.md"),
    ("plan", "Design & Plan", "PLAN.md"),
]

_CSS = """
:root{--bg:#0f1320;--panel:#161b2b;--card:#1a2032;--ink:#e7ecf5;--mut:#8a97b3;
--acc:#5b8cff;--bd:#283150;--ok:#3ecf8e;--code:#0d1120;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,sans-serif}
a{color:var(--acc);text-decoration:none}a:hover{text-decoration:underline}
#wrap{display:flex;min-height:100vh}
#nav{position:sticky;top:0;align-self:flex-start;width:240px;height:100vh;overflow:auto;
background:var(--panel);border-right:1px solid var(--bd);padding:22px 16px}
#nav h1{font-size:15px;margin:0 0 2px}#nav .tag{color:var(--mut);font-size:12px;margin-bottom:18px}
#nav a{display:block;color:var(--ink);padding:7px 10px;border-radius:7px;font-size:14px}
#nav a:hover{background:var(--card);text-decoration:none}
#nav a.doc{font-weight:600;margin-top:12px}
#nav a.sub{color:var(--mut);font-size:13px;padding-left:20px}
main{flex:1;max-width:920px;padding:40px 48px 80px}
section{display:none}section.active{display:block}
h1,h2,h3{line-height:1.3}h1{font-size:26px;border-bottom:1px solid var(--bd);padding-bottom:10px}
h2{font-size:21px;margin-top:34px;border-bottom:1px solid var(--bd);padding-bottom:6px}
h3{font-size:17px;margin-top:24px;color:#cdd6ea}
code{background:var(--code);padding:2px 6px;border-radius:5px;font-size:13px;
font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
pre{background:var(--code);border:1px solid var(--bd);border-radius:10px;padding:14px 16px;overflow:auto}
pre code{background:none;padding:0}
blockquote{border-left:3px solid var(--acc);margin:14px 0;padding:6px 16px;background:var(--card);
border-radius:0 8px 8px 0;color:#cdd6ea}
table{border-collapse:collapse;width:100%;margin:14px 0;font-size:13.5px}
th,td{border:1px solid var(--bd);padding:7px 10px;text-align:left;vertical-align:top}
th{background:var(--card);color:#cdd6ea}
tr:nth-child(even) td{background:#141a29}
hr{border:0;border-top:1px solid var(--bd);margin:28px 0}
.banner{background:linear-gradient(90deg,#1a2032,#161b2b);border:1px solid var(--bd);
border-radius:12px;padding:16px 20px;margin-bottom:26px}
.banner b{color:var(--ok)}
@media(max-width:760px){#nav{display:none}main{padding:24px}}
"""

_JS = """
function show(id){
 document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',s.id===id));
 document.querySelectorAll('#nav a.doc').forEach(a=>a.style.background=(a.dataset.t===id)?'#1a2032':'');
 history.replaceState(null,'','#'+id);
 document.querySelector('main').scrollTo(0,0);
}
window.addEventListener('DOMContentLoaded',()=>{
 const h=location.hash.replace('#','');
 show(document.getElementById(h)?h:'readme');
});
"""


def _render(md_text: str) -> str:
    return markdown.markdown(
        md_text, extensions=["tables", "fenced_code", "toc", "sane_lists"],
        extension_configs={"toc": {"permalink": False}})


def build() -> pathlib.Path:
    sections, nav = [], []
    for sid, title, fname in DOCS:
        md_text = (ROOT / fname).read_text(encoding="utf-8")
        html = _render(md_text)
        sections.append(f'<section id="{sid}">{html}</section>')
        # sidebar: doc link + its H2 anchors
        subs = re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', html)
        sub_links = "".join(
            f'<a class="sub" href="#{sid}" onclick="show(\'{sid}\')">{re.sub("<[^>]+>", "", t)}</a>'
            for _id, t in subs[:8])
        nav.append(
            f'<a class="doc" data-t="{sid}" href="#{sid}" onclick="show(\'{sid}\');return false">{title}</a>{sub_links}')

    out = ROOT / "docs" / "index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ad Integrity Scanner — Documentation</title><style>{_CSS}</style></head>
<body><div id="wrap">
<aside id="nav"><h1>Ad Integrity Scanner</h1><div class="tag">Documentation</div>
{''.join(nav)}
<hr><a class="sub" href="https://github.com/kenrona/ad-integrity-scanner">GitHub ↗</a></aside>
<main>
<div class="banner">Generated from the repo markdown via <code>python -m app.docsite</code>.
Metric field reference is in <b>Data Dictionary</b>; scoring logic in <b>Metrics</b>.</div>
{''.join(sections)}
</main></div><script>{_JS}</script></body></html>""", encoding="utf-8")
    return out


if __name__ == "__main__":
    p = build()
    print(f"wrote {p} ({p.stat().st_size // 1024} KB)")
